export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
		user: {
			username: "Nobita 1",
			profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "Nobita 2",
			profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
		user: {
			username: "Nobita 3",
			profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
		user: {
			username: "Nobita 4",
			profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "Nobita 5",
		profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "Nobita 6",
		profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "Nobita 7",
		profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "Nobita 8",
		profileImg: "https://imgs.search.brave.com/EwOyFX85KluR1etw_SpvA3ho6qt3yzZpaOkhW-aemnU/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9waG90/b3Nub3cub3JnL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L25vYml0YS1waG90/b18xNi5qcGc",
	},
];